# docker-compose.dev.yml
services:
  app:
    command: python -u app.py
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - .:/app                         # live code (hot-reload)
      - doe-calculator_bids:/app/shared:ro   # SMB share from base compose
